#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinAlertDialog.Resource", IsApplication=true)]

namespace XamarinAlertDialog
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050009
			public const int age = 2131034121;
			
			// aapt resource value: 0x7f050001
			public const int button1 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int button2 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int button3 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int button4 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int button5 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int button6 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int button7 = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int listView1 = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int name = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int sex = 2131034122;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ListViewSimpleTest = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ListViewTest = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int PartListViewTest = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ScrollTest = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
